<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KecamatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $kecamatan = [
            ['kota_id' => '1', 'kecamatan' => 'NANGGUNG'],
            ['kota_id' => '1', 'kecamatan' => 'LEUWILIANG'],
            ['kota_id' => '1', 'kecamatan' => 'LEUWISADENG'],
            ['kota_id' => '1', 'kecamatan' => 'PAMIJAHAN'],
            ['kota_id' => '1', 'kecamatan' => 'CIBUNGBULANG'],
            ['kota_id' => '1', 'kecamatan' => 'CIAMPEA'],
            ['kota_id' => '1', 'kecamatan' => 'TENJOLAYA'],
            ['kota_id' => '1', 'kecamatan' => 'DRAMAGA'],
            ['kota_id' => '1', 'kecamatan' => 'CIOMAS'],
            ['kota_id' => '1', 'kecamatan' => 'TAMANSARI'],
            ['kota_id' => '1', 'kecamatan' => 'CIJERUK'],
            ['kota_id' => '1', 'kecamatan' => 'CIGOMBONG'],
            ['kota_id' => '1', 'kecamatan' => 'CARINGIN'],
            ['kota_id' => '1', 'kecamatan' => 'CIAWI'],
            ['kota_id' => '1', 'kecamatan' => 'CISARUA'],
            ['kota_id' => '1', 'kecamatan' => 'MEGAMENDUNG'],
            ['kota_id' => '1', 'kecamatan' => 'SUKARAJA'],
            ['kota_id' => '1', 'kecamatan' => 'BABAKAN MADANG'],
            ['kota_id' => '1', 'kecamatan' => 'SUKAMAKMUR'],
            ['kota_id' => '1', 'kecamatan' => 'CARIU'],
            ['kota_id' => '1', 'kecamatan' => 'TANJUNGSARI'],
            ['kota_id' => '1', 'kecamatan' => 'JONGGOL'],
            ['kota_id' => '1', 'kecamatan' => 'CILEUNGSI'],
            ['kota_id' => '1', 'kecamatan' => 'KELAPA NUNGGAL'],
            ['kota_id' => '1', 'kecamatan' => 'GUNUNG PUTRI'],
            ['kota_id' => '1', 'kecamatan' => 'CITEUREUP'],
            ['kota_id' => '1', 'kecamatan' => 'CIBINONG'],
            ['kota_id' => '1', 'kecamatan' => 'BOJONG GEDE'],
            ['kota_id' => '1', 'kecamatan' => 'TAJUR HALANG'],
            ['kota_id' => '1', 'kecamatan' => 'KEMANG'],
            ['kota_id' => '1', 'kecamatan' => 'RANCA BUNGUR'],
            ['kota_id' => '1', 'kecamatan' => 'PARUNG'],
            ['kota_id' => '1', 'kecamatan' => 'CISEENG'],
            ['kota_id' => '1', 'kecamatan' => 'GUNUNG SINDUR'],
            ['kota_id' => '1', 'kecamatan' => 'RUMPIN'],
            ['kota_id' => '1', 'kecamatan' => 'CIGUDEG'],
            ['kota_id' => '1', 'kecamatan' => 'SUKAJAYA'],
            ['kota_id' => '1', 'kecamatan' => 'JASINGA'],
            ['kota_id' => '1', 'kecamatan' => 'TENJO'],
            ['kota_id' => '1', 'kecamatan' => 'PARUNG PANJANG'],
            ['kota_id' => '2', 'kecamatan' => 'CIEMAS'],
            ['kota_id' => '2', 'kecamatan' => 'CIRACAP'],
            ['kota_id' => '2', 'kecamatan' => 'WALURAN'],
            ['kota_id' => '2', 'kecamatan' => 'SURADE'],
            ['kota_id' => '2', 'kecamatan' => 'CIBITUNG'],
            ['kota_id' => '2', 'kecamatan' => 'JAMPANG KULON'],
            ['kota_id' => '2', 'kecamatan' => 'CIMANGGU'],
            ['kota_id' => '2', 'kecamatan' => 'KALI BUNDER'],
            ['kota_id' => '2', 'kecamatan' => 'TEGAL BULEUD'],
            ['kota_id' => '2', 'kecamatan' => 'CIDOLOG'],
            ['kota_id' => '2', 'kecamatan' => 'SAGARANTEN'],
            ['kota_id' => '2', 'kecamatan' => 'CIDADAP'],
            ['kota_id' => '2', 'kecamatan' => 'CURUGKEMBAR'],
            ['kota_id' => '2', 'kecamatan' => 'PABUARAN'],
            ['kota_id' => '2', 'kecamatan' => 'LENGKONG'],
            ['kota_id' => '2', 'kecamatan' => 'PALABUHANRATU'],
            ['kota_id' => '2', 'kecamatan' => 'SIMPENAN'],
            ['kota_id' => '2', 'kecamatan' => 'WARUNG KIARA'],
            ['kota_id' => '2', 'kecamatan' => 'BANTARGADUNG'],
            ['kota_id' => '2', 'kecamatan' => 'JAMPANG TENGAH'],
            ['kota_id' => '2', 'kecamatan' => 'PURABAYA'],
            ['kota_id' => '2', 'kecamatan' => 'CIKEMBAR'],
            ['kota_id' => '2', 'kecamatan' => 'NYALINDUNG'],
            ['kota_id' => '2', 'kecamatan' => 'GEGER BITUNG'],
            ['kota_id' => '2', 'kecamatan' => 'SUKARAJA'],
            ['kota_id' => '2', 'kecamatan' => 'KEBONPEDES'],
            ['kota_id' => '2', 'kecamatan' => 'CIREUNGHAS'],
            ['kota_id' => '2', 'kecamatan' => 'SUKALARANG'],
            ['kota_id' => '2', 'kecamatan' => 'SUKABUMI'],
            ['kota_id' => '2', 'kecamatan' => 'KADUDAMPIT'],
            ['kota_id' => '2', 'kecamatan' => 'CISAAT'],
            ['kota_id' => '2', 'kecamatan' => 'GUNUNGGURUH'],
            ['kota_id' => '2', 'kecamatan' => 'CIBADAK'],
            ['kota_id' => '2', 'kecamatan' => 'CICANTAYAN'],
            ['kota_id' => '2', 'kecamatan' => 'CARINGIN'],
            ['kota_id' => '2', 'kecamatan' => 'NAGRAK'],
            ['kota_id' => '2', 'kecamatan' => 'CIAMBAR'],
            ['kota_id' => '2', 'kecamatan' => 'CICURUG'],
            ['kota_id' => '2', 'kecamatan' => 'CIDAHU'],
            ['kota_id' => '2', 'kecamatan' => 'PARAKAN SALAK'],
            ['kota_id' => '2', 'kecamatan' => 'PARUNG KUDA'],
            ['kota_id' => '2', 'kecamatan' => 'BOJONG GENTENG'],
            ['kota_id' => '2', 'kecamatan' => 'KALAPA NUNGGAL'],
            ['kota_id' => '2', 'kecamatan' => 'CIKIDANG'],
            ['kota_id' => '2', 'kecamatan' => 'CISOLOK'],
            ['kota_id' => '2', 'kecamatan' => 'CIKAKAK'],
            ['kota_id' => '2', 'kecamatan' => 'KABANDUNGAN'],
            ['kota_id' => '3', 'kecamatan' => 'AGRABINTA'],
            ['kota_id' => '3', 'kecamatan' => 'LELES'],
            ['kota_id' => '3', 'kecamatan' => 'SINDANGBARANG'],
            ['kota_id' => '3', 'kecamatan' => 'CIDAUN'],
            ['kota_id' => '3', 'kecamatan' => 'NARINGGUL'],
            ['kota_id' => '3', 'kecamatan' => 'CIBINONG'],
            ['kota_id' => '3', 'kecamatan' => 'CIKADU'],
            ['kota_id' => '3', 'kecamatan' => 'TANGGEUNG'],
            ['kota_id' => '3', 'kecamatan' => 'PASIRKUDA'],
            ['kota_id' => '3', 'kecamatan' => 'KADUPANDAK'],
            ['kota_id' => '3', 'kecamatan' => 'CIJATI'],
            ['kota_id' => '3', 'kecamatan' => 'TAKOKAK'],
            ['kota_id' => '3', 'kecamatan' => 'SUKANAGARA'],
            ['kota_id' => '3', 'kecamatan' => 'PAGELARAN'],
            ['kota_id' => '3', 'kecamatan' => 'CAMPAKA'],
            ['kota_id' => '3', 'kecamatan' => 'CAMPAKA MULYA'],
            ['kota_id' => '3', 'kecamatan' => 'CIBEBER'],
            ['kota_id' => '3', 'kecamatan' => 'WARUNGKONDANG'],
            ['kota_id' => '3', 'kecamatan' => 'GEKBRONG'],
            ['kota_id' => '3', 'kecamatan' => 'CILAKU'],
            ['kota_id' => '3', 'kecamatan' => 'SUKALUYU'],
            ['kota_id' => '3', 'kecamatan' => 'BOJONGPICUNG'],
            ['kota_id' => '3', 'kecamatan' => 'HAURWANGI'],
            ['kota_id' => '3', 'kecamatan' => 'CIRANJANG'],
            ['kota_id' => '3', 'kecamatan' => 'MANDE'],
            ['kota_id' => '3', 'kecamatan' => 'KARANGTENGAH'],
            ['kota_id' => '3', 'kecamatan' => 'CIANJUR'],
            ['kota_id' => '3', 'kecamatan' => 'CUGENANG'],
            ['kota_id' => '3', 'kecamatan' => 'PACET'],
            ['kota_id' => '3', 'kecamatan' => 'CIPANAS'],
            ['kota_id' => '3', 'kecamatan' => 'SUKARESMI'],
            ['kota_id' => '3', 'kecamatan' => 'CIKALONGKULON'],
            ['kota_id' => '4', 'kecamatan' => 'CIWIDEY'],
            ['kota_id' => '4', 'kecamatan' => 'RANCABALI'],
            ['kota_id' => '4', 'kecamatan' => 'PASIRJAMBU'],
            ['kota_id' => '4', 'kecamatan' => 'CIMAUNG'],
            ['kota_id' => '4', 'kecamatan' => 'PANGALENGAN'],
            ['kota_id' => '4', 'kecamatan' => 'KERTASARI'],
            ['kota_id' => '4', 'kecamatan' => 'PACET'],
            ['kota_id' => '4', 'kecamatan' => 'IBUN'],
            ['kota_id' => '4', 'kecamatan' => 'PASEH'],
            ['kota_id' => '4', 'kecamatan' => 'CIKANCUNG'],
            ['kota_id' => '4', 'kecamatan' => 'CICALENGKA'],
            ['kota_id' => '4', 'kecamatan' => 'NAGREG'],
            ['kota_id' => '4', 'kecamatan' => 'RANCAEKEK'],
            ['kota_id' => '4', 'kecamatan' => 'MAJALAYA'],
            ['kota_id' => '4', 'kecamatan' => 'SOLOKAN JERUK'],
            ['kota_id' => '4', 'kecamatan' => 'CIPARAY'],
            ['kota_id' => '4', 'kecamatan' => 'BALEENDAH'],
            ['kota_id' => '4', 'kecamatan' => 'ARJASARI'],
            ['kota_id' => '4', 'kecamatan' => 'BANJARAN'],
            ['kota_id' => '4', 'kecamatan' => 'CANGKUANG'],
            ['kota_id' => '4', 'kecamatan' => 'PAMEUNGPEUK'],
            ['kota_id' => '4', 'kecamatan' => 'KATAPANG'],
            ['kota_id' => '4', 'kecamatan' => 'SOREANG'],
            ['kota_id' => '4', 'kecamatan' => 'KUTAWARINGIN'],
            ['kota_id' => '4', 'kecamatan' => 'MARGAASIH'],
            ['kota_id' => '4', 'kecamatan' => 'MARGAHAYU'],
            ['kota_id' => '4', 'kecamatan' => 'DAYEUHKOLOT'],
            ['kota_id' => '4', 'kecamatan' => 'BOJONGSOANG'],
            ['kota_id' => '4', 'kecamatan' => 'CILEUNYI'],
            ['kota_id' => '4', 'kecamatan' => 'CILENGKRANG'],
            ['kota_id' => '4', 'kecamatan' => 'CIMENYAN'],
            ['kota_id' => '5', 'kecamatan' => 'CISEWU'],
            ['kota_id' => '5', 'kecamatan' => 'CARINGIN'],
            ['kota_id' => '5', 'kecamatan' => 'TALEGONG'],
            ['kota_id' => '5', 'kecamatan' => 'BUNGBULANG'],
            ['kota_id' => '5', 'kecamatan' => 'MEKARMUKTI'],
            ['kota_id' => '5', 'kecamatan' => 'PAMULIHAN'],
            ['kota_id' => '5', 'kecamatan' => 'PAKENJENG'],
            ['kota_id' => '5', 'kecamatan' => 'CIKELET'],
            ['kota_id' => '5', 'kecamatan' => 'PAMEUNGPEUK'],
            ['kota_id' => '5', 'kecamatan' => 'CIBALONG'],
            ['kota_id' => '5', 'kecamatan' => 'CISOMPET'],
            ['kota_id' => '5', 'kecamatan' => 'PEUNDEUY'],
            ['kota_id' => '5', 'kecamatan' => 'SINGAJAYA'],
            ['kota_id' => '5', 'kecamatan' => 'CIHURIP'],
            ['kota_id' => '5', 'kecamatan' => 'CIKAJANG'],
            ['kota_id' => '5', 'kecamatan' => 'BANJARWANGI'],
            ['kota_id' => '5', 'kecamatan' => 'CILAWU'],
            ['kota_id' => '5', 'kecamatan' => 'BAYONGBONG'],
            ['kota_id' => '5', 'kecamatan' => 'CIGEDUG'],
            ['kota_id' => '5', 'kecamatan' => 'CISURUPAN'],
            ['kota_id' => '5', 'kecamatan' => 'SUKARESMI'],
            ['kota_id' => '5', 'kecamatan' => 'SAMARANG'],
            ['kota_id' => '5', 'kecamatan' => 'PASIRWANGI'],
            ['kota_id' => '5', 'kecamatan' => 'TAROGONG KIDUL'],
            ['kota_id' => '5', 'kecamatan' => 'TAROGONG KALER'],
            ['kota_id' => '5', 'kecamatan' => 'GARUT KOTA'],
            ['kota_id' => '5', 'kecamatan' => 'KARANGPAWITAN'],
            ['kota_id' => '5', 'kecamatan' => 'WANARAJA'],
            ['kota_id' => '5', 'kecamatan' => 'SUCINARAJA'],
            ['kota_id' => '5', 'kecamatan' => 'PANGATIKAN'],
            ['kota_id' => '5', 'kecamatan' => 'SUKAWENING'],
            ['kota_id' => '5', 'kecamatan' => 'KARANGTENGAH'],
            ['kota_id' => '5', 'kecamatan' => 'BANYURESMI'],
            ['kota_id' => '5', 'kecamatan' => 'LELES'],
            ['kota_id' => '5', 'kecamatan' => 'LEUWIGOONG'],
            ['kota_id' => '5', 'kecamatan' => 'CIBATU'],
            ['kota_id' => '5', 'kecamatan' => 'KERSAMANAH'],
            ['kota_id' => '5', 'kecamatan' => 'CIBIUK'],
            ['kota_id' => '5', 'kecamatan' => 'KADUNGORA'],
            ['kota_id' => '5', 'kecamatan' => 'BLUBUR LIMBANGAN'],
            ['kota_id' => '5', 'kecamatan' => 'SELAAWI'],
            ['kota_id' => '5', 'kecamatan' => 'MALANGBONG'],
            ['kota_id' => '6', 'kecamatan' => 'CIPATUJAH'],
            ['kota_id' => '6', 'kecamatan' => 'KARANGNUNGGAL'],
            ['kota_id' => '6', 'kecamatan' => 'CIKALONG'],
            ['kota_id' => '6', 'kecamatan' => 'PANCATENGAH'],
            ['kota_id' => '6', 'kecamatan' => 'CIKATOMAS'],
            ['kota_id' => '6', 'kecamatan' => 'CIBALONG'],
            ['kota_id' => '6', 'kecamatan' => 'PARUNGPONTENG'],
            ['kota_id' => '6', 'kecamatan' => 'BANTARKALONG'],
            ['kota_id' => '6', 'kecamatan' => 'BOJONGASIH'],
            ['kota_id' => '6', 'kecamatan' => 'CULAMEGA'],
            ['kota_id' => '6', 'kecamatan' => 'BOJONGGAMBIR'],
            ['kota_id' => '6', 'kecamatan' => 'SODONGHILIR'],
            ['kota_id' => '6', 'kecamatan' => 'TARAJU'],
            ['kota_id' => '6', 'kecamatan' => 'SALAWU'],
            ['kota_id' => '6', 'kecamatan' => 'PUSPAHIANG'],
            ['kota_id' => '6', 'kecamatan' => 'TANJUNGJAYA'],
            ['kota_id' => '6', 'kecamatan' => 'SUKARAJA'],
            ['kota_id' => '6', 'kecamatan' => 'SALOPA'],
            ['kota_id' => '6', 'kecamatan' => 'JATIWARAS'],
            ['kota_id' => '6', 'kecamatan' => 'CINEAM'],
            ['kota_id' => '6', 'kecamatan' => 'KARANGJAYA'],
            ['kota_id' => '6', 'kecamatan' => 'MANONJAYA'],
            ['kota_id' => '6', 'kecamatan' => 'GUNUNGTANJUNG'],
            ['kota_id' => '6', 'kecamatan' => 'SINGAPARNA'],
            ['kota_id' => '6', 'kecamatan' => 'SUKARAME'],
            ['kota_id' => '6', 'kecamatan' => 'MANGUNREJA'],
            ['kota_id' => '6', 'kecamatan' => 'CIGALONTANG'],
            ['kota_id' => '6', 'kecamatan' => 'LEUWISARI'],
            ['kota_id' => '6', 'kecamatan' => 'SARIWANGI'],
            ['kota_id' => '6', 'kecamatan' => 'PADAKEMBANG'],
            ['kota_id' => '6', 'kecamatan' => 'SUKARATU'],
            ['kota_id' => '6', 'kecamatan' => 'CISAYONG'],
            ['kota_id' => '6', 'kecamatan' => 'SUKAHENING'],
            ['kota_id' => '6', 'kecamatan' => 'RAJAPOLAH'],
            ['kota_id' => '6', 'kecamatan' => 'JAMANIS'],
            ['kota_id' => '6', 'kecamatan' => 'CIAWI'],
            ['kota_id' => '6', 'kecamatan' => 'KADIPATEN'],
            ['kota_id' => '6', 'kecamatan' => 'PAGERAGEUNG'],
            ['kota_id' => '6', 'kecamatan' => 'SUKARESIK'],
            ['kota_id' => '7', 'kecamatan' => 'BANJARSARI'],
            ['kota_id' => '7', 'kecamatan' => 'LAKBOK'],
            ['kota_id' => '7', 'kecamatan' => 'PURWADADI'],
            ['kota_id' => '7', 'kecamatan' => 'PAMARICAN'],
            ['kota_id' => '7', 'kecamatan' => 'CIDOLOG'],
            ['kota_id' => '7', 'kecamatan' => 'CIMARAGAS'],
            ['kota_id' => '7', 'kecamatan' => 'CIJEUNGJING'],
            ['kota_id' => '7', 'kecamatan' => 'CISAGA'],
            ['kota_id' => '7', 'kecamatan' => 'TAMBAKSARI'],
            ['kota_id' => '7', 'kecamatan' => 'RANCAH'],
            ['kota_id' => '7', 'kecamatan' => 'RAJADESA'],
            ['kota_id' => '7', 'kecamatan' => 'SUKADANA'],
            ['kota_id' => '7', 'kecamatan' => 'CIAMIS'],
            ['kota_id' => '7', 'kecamatan' => 'BAREGBEG'],
            ['kota_id' => '7', 'kecamatan' => 'CIKONENG'],
            ['kota_id' => '7', 'kecamatan' => 'SINDANGKASIH'],
            ['kota_id' => '7', 'kecamatan' => 'CIHAURBEUTI'],
            ['kota_id' => '7', 'kecamatan' => 'SADANANYA'],
            ['kota_id' => '7', 'kecamatan' => 'CIPAKU'],
            ['kota_id' => '7', 'kecamatan' => 'JATINAGARA'],
            ['kota_id' => '7', 'kecamatan' => 'PANAWANGAN'],
            ['kota_id' => '7', 'kecamatan' => 'KAWALI'],
            ['kota_id' => '7', 'kecamatan' => 'LUMBUNG'],
            ['kota_id' => '7', 'kecamatan' => 'PANJALU'],
            ['kota_id' => '7', 'kecamatan' => 'SUKAMANTRI'],
            ['kota_id' => '7', 'kecamatan' => 'PANUMBANGAN'],
            ['kota_id' => '8', 'kecamatan' => 'DARMA'],
            ['kota_id' => '8', 'kecamatan' => 'KADUGEDE'],
            ['kota_id' => '8', 'kecamatan' => 'NUSAHERANG'],
            ['kota_id' => '8', 'kecamatan' => 'CINIRU'],
            ['kota_id' => '8', 'kecamatan' => 'HANTARA'],
            ['kota_id' => '8', 'kecamatan' => 'SELAJAMBE'],
            ['kota_id' => '8', 'kecamatan' => 'SUBANG'],
            ['kota_id' => '8', 'kecamatan' => 'CILEBAK'],
            ['kota_id' => '8', 'kecamatan' => 'CIWARU'],
            ['kota_id' => '8', 'kecamatan' => 'KARANGKANCANA'],
            ['kota_id' => '8', 'kecamatan' => 'CIBINGBIN'],
            ['kota_id' => '8', 'kecamatan' => 'CIBEUREUM'],
            ['kota_id' => '8', 'kecamatan' => 'LURAGUNG'],
            ['kota_id' => '8', 'kecamatan' => 'CIMAHI'],
            ['kota_id' => '8', 'kecamatan' => 'CIDAHU'],
            ['kota_id' => '8', 'kecamatan' => 'KALIMANGGIS'],
            ['kota_id' => '8', 'kecamatan' => 'CIAWIGEBANG'],
            ['kota_id' => '8', 'kecamatan' => 'CIPICUNG'],
            ['kota_id' => '8', 'kecamatan' => 'LEBAKWANGI'],
            ['kota_id' => '8', 'kecamatan' => 'MALEBER'],
            ['kota_id' => '8', 'kecamatan' => 'GARAWANGI'],
            ['kota_id' => '8', 'kecamatan' => 'SINDANGAGUNG'],
            ['kota_id' => '8', 'kecamatan' => 'KUNINGAN'],
            ['kota_id' => '8', 'kecamatan' => 'CIGUGUR'],
            ['kota_id' => '8', 'kecamatan' => 'KRAMATMULYA'],
            ['kota_id' => '8', 'kecamatan' => 'JALAKSANA'],
            ['kota_id' => '8', 'kecamatan' => 'JAPARA'],
            ['kota_id' => '8', 'kecamatan' => 'CILIMUS'],
            ['kota_id' => '8', 'kecamatan' => 'CIGANDAMEKAR'],
            ['kota_id' => '8', 'kecamatan' => 'MANDIRANCAN'],
            ['kota_id' => '8', 'kecamatan' => 'PANCALANG'],
            ['kota_id' => '8', 'kecamatan' => 'PASAWAHAN'],
            ['kota_id' => '9', 'kecamatan' => 'WALED'],
            ['kota_id' => '9', 'kecamatan' => 'PASALEMAN'],
            ['kota_id' => '9', 'kecamatan' => 'CILEDUG'],
            ['kota_id' => '9', 'kecamatan' => 'PABUARAN'],
            ['kota_id' => '9', 'kecamatan' => 'LOSARI'],
            ['kota_id' => '9', 'kecamatan' => 'PABEDILAN'],
            ['kota_id' => '9', 'kecamatan' => 'BABAKAN'],
            ['kota_id' => '9', 'kecamatan' => 'GEBANG'],
            ['kota_id' => '9', 'kecamatan' => 'KARANGSEMBUNG'],
            ['kota_id' => '9', 'kecamatan' => 'KARANGWARENG'],
            ['kota_id' => '9', 'kecamatan' => 'LEMAHABANG'],
            ['kota_id' => '9', 'kecamatan' => 'SUSUKANLEBAK'],
            ['kota_id' => '9', 'kecamatan' => 'SEDONG'],
            ['kota_id' => '9', 'kecamatan' => 'ASTANAJAPURA'],
            ['kota_id' => '9', 'kecamatan' => 'PANGENAN'],
            ['kota_id' => '9', 'kecamatan' => 'MUNDU'],
            ['kota_id' => '9', 'kecamatan' => 'BEBER'],
            ['kota_id' => '9', 'kecamatan' => 'GREGED'],
            ['kota_id' => '9', 'kecamatan' => 'TALUN'],
            ['kota_id' => '9', 'kecamatan' => 'SUMBER'],
            ['kota_id' => '9', 'kecamatan' => 'DUKUPUNTANG'],
            ['kota_id' => '9', 'kecamatan' => 'PALIMANAN'],
            ['kota_id' => '9', 'kecamatan' => 'PLUMBON'],
            ['kota_id' => '9', 'kecamatan' => 'DEPOK'],
            ['kota_id' => '9', 'kecamatan' => 'WERU'],
            ['kota_id' => '9', 'kecamatan' => 'PLERED'],
            ['kota_id' => '9', 'kecamatan' => 'TENGAH TANI'],
            ['kota_id' => '9', 'kecamatan' => 'KEDAWUNG'],
            ['kota_id' => '9', 'kecamatan' => 'GUNUNGJATI'],
            ['kota_id' => '9', 'kecamatan' => 'KAPETAKAN'],
            ['kota_id' => '9', 'kecamatan' => 'SURANENGGALA'],
            ['kota_id' => '9', 'kecamatan' => 'KLANGENAN'],
            ['kota_id' => '9', 'kecamatan' => 'JAMBLANG'],
            ['kota_id' => '9', 'kecamatan' => 'ARJAWINANGUN'],
            ['kota_id' => '9', 'kecamatan' => 'PANGURAGAN'],
            ['kota_id' => '9', 'kecamatan' => 'CIWARINGIN'],
            ['kota_id' => '9', 'kecamatan' => 'GEMPOL'],
            ['kota_id' => '9', 'kecamatan' => 'SUSUKAN'],
            ['kota_id' => '9', 'kecamatan' => 'GEGESIK'],
            ['kota_id' => '9', 'kecamatan' => 'KALIWEDI'],
            ['kota_id' => '10', 'kecamatan' => 'LEMAHSUGIH'],
            ['kota_id' => '10', 'kecamatan' => 'BANTARUJEG'],
            ['kota_id' => '10', 'kecamatan' => 'MALAUSMA'],
            ['kota_id' => '10', 'kecamatan' => 'CIKIJING'],
            ['kota_id' => '10', 'kecamatan' => 'CINGAMBUL'],
            ['kota_id' => '10', 'kecamatan' => 'TALAGA'],
            ['kota_id' => '10', 'kecamatan' => 'BANJARAN'],
            ['kota_id' => '10', 'kecamatan' => 'ARGAPURA'],
            ['kota_id' => '10', 'kecamatan' => 'MAJA'],
            ['kota_id' => '10', 'kecamatan' => 'MAJALENGKA'],
            ['kota_id' => '10', 'kecamatan' => 'CIGASONG'],
            ['kota_id' => '10', 'kecamatan' => 'SUKAHAJI'],
            ['kota_id' => '10', 'kecamatan' => 'SINDANG'],
            ['kota_id' => '10', 'kecamatan' => 'RAJAGALUH'],
            ['kota_id' => '10', 'kecamatan' => 'SINDANGWANGI'],
            ['kota_id' => '10', 'kecamatan' => 'LEUWIMUNDING'],
            ['kota_id' => '10', 'kecamatan' => 'PALASAH'],
            ['kota_id' => '10', 'kecamatan' => 'JATIWANGI'],
            ['kota_id' => '10', 'kecamatan' => 'DAWUAN'],
            ['kota_id' => '10', 'kecamatan' => 'KASOKANDEL'],
            ['kota_id' => '10', 'kecamatan' => 'PANYINGKIRAN'],
            ['kota_id' => '10', 'kecamatan' => 'KADIPATEN'],
            ['kota_id' => '10', 'kecamatan' => 'KERTAJATI'],
            ['kota_id' => '10', 'kecamatan' => 'JATITUJUH'],
            ['kota_id' => '10', 'kecamatan' => 'LIGUNG'],
            ['kota_id' => '10', 'kecamatan' => 'SUMBERJAYA'],
            ['kota_id' => '11', 'kecamatan' => 'JATINANGOR'],
            ['kota_id' => '11', 'kecamatan' => 'CIMANGGUNG'],
            ['kota_id' => '11', 'kecamatan' => 'TANJUNGSARI'],
            ['kota_id' => '11', 'kecamatan' => 'SUKASARI'],
            ['kota_id' => '11', 'kecamatan' => 'PAMULIHAN'],
            ['kota_id' => '11', 'kecamatan' => 'RANCAKALONG'],
            ['kota_id' => '11', 'kecamatan' => 'SUMEDANG SELATAN'],
            ['kota_id' => '11', 'kecamatan' => 'SUMEDANG UTARA'],
            ['kota_id' => '11', 'kecamatan' => 'GANEAS'],
            ['kota_id' => '11', 'kecamatan' => 'SITURAJA'],
            ['kota_id' => '11', 'kecamatan' => 'CISITU'],
            ['kota_id' => '11', 'kecamatan' => 'DARMARAJA'],
            ['kota_id' => '11', 'kecamatan' => 'CIBUGEL'],
            ['kota_id' => '11', 'kecamatan' => 'WADO'],
            ['kota_id' => '11', 'kecamatan' => 'JATINUNGGAL'],
            ['kota_id' => '11', 'kecamatan' => 'JATIGEDE'],
            ['kota_id' => '11', 'kecamatan' => 'TOMO'],
            ['kota_id' => '11', 'kecamatan' => 'UJUNG JAYA'],
            ['kota_id' => '11', 'kecamatan' => 'CONGGEANG'],
            ['kota_id' => '11', 'kecamatan' => 'PASEH'],
            ['kota_id' => '11', 'kecamatan' => 'CIMALAKA'],
            ['kota_id' => '11', 'kecamatan' => 'CISARUA'],
            ['kota_id' => '11', 'kecamatan' => 'TANJUNGKERTA'],
            ['kota_id' => '11', 'kecamatan' => 'TANJUNGMEDAR'],
            ['kota_id' => '11', 'kecamatan' => 'BUAHDUA'],
            ['kota_id' => '11', 'kecamatan' => 'SURIAN'],
            ['kota_id' => '12', 'kecamatan' => 'HAURGEULIS'],
            ['kota_id' => '12', 'kecamatan' => 'GANTAR'],
            ['kota_id' => '12', 'kecamatan' => 'KROYA'],
            ['kota_id' => '12', 'kecamatan' => 'GABUSWETAN'],
            ['kota_id' => '12', 'kecamatan' => 'CIKEDUNG'],
            ['kota_id' => '12', 'kecamatan' => 'TERISI'],
            ['kota_id' => '12', 'kecamatan' => 'LELEA'],
            ['kota_id' => '12', 'kecamatan' => 'BANGODUA'],
            ['kota_id' => '12', 'kecamatan' => 'TUKDANA'],
            ['kota_id' => '12', 'kecamatan' => 'WIDASARI'],
            ['kota_id' => '12', 'kecamatan' => 'KERTASEMAYA'],
            ['kota_id' => '12', 'kecamatan' => 'SUKAGUMIWANG'],
            ['kota_id' => '12', 'kecamatan' => 'KRANGKENG'],
            ['kota_id' => '12', 'kecamatan' => 'KARANGAMPEL'],
            ['kota_id' => '12', 'kecamatan' => 'KEDOKAN BUNDER'],
            ['kota_id' => '12', 'kecamatan' => 'JUNTINYUAT'],
            ['kota_id' => '12', 'kecamatan' => 'SLIYEG'],
            ['kota_id' => '12', 'kecamatan' => 'JATIBARANG'],
            ['kota_id' => '12', 'kecamatan' => 'BALONGAN'],
            ['kota_id' => '12', 'kecamatan' => 'INDRAMAYU'],
            ['kota_id' => '12', 'kecamatan' => 'SINDANG'],
            ['kota_id' => '12', 'kecamatan' => 'CANTIGI'],
            ['kota_id' => '12', 'kecamatan' => 'PASEKAN'],
            ['kota_id' => '12', 'kecamatan' => 'LOHBENER'],
            ['kota_id' => '12', 'kecamatan' => 'ARAHAN'],
            ['kota_id' => '12', 'kecamatan' => 'LOSARANG'],
            ['kota_id' => '12', 'kecamatan' => 'KANDANGHAUR'],
            ['kota_id' => '12', 'kecamatan' => 'BONGAS'],
            ['kota_id' => '12', 'kecamatan' => 'ANJATAN'],
            ['kota_id' => '12', 'kecamatan' => 'SUKRA'],
            ['kota_id' => '12', 'kecamatan' => 'PATROL'],
            ['kota_id' => '13', 'kecamatan' => 'SAGALAHERANG'],
            ['kota_id' => '13', 'kecamatan' => 'SERANGPANJANG'],
            ['kota_id' => '13', 'kecamatan' => 'JALANCAGAK'],
            ['kota_id' => '13', 'kecamatan' => 'CIATER'],
            ['kota_id' => '13', 'kecamatan' => 'CISALAK'],
            ['kota_id' => '13', 'kecamatan' => 'KASOMALANG'],
            ['kota_id' => '13', 'kecamatan' => 'TANJUNGSIANG'],
            ['kota_id' => '13', 'kecamatan' => 'CIJAMBE'],
            ['kota_id' => '13', 'kecamatan' => 'CIBOGO'],
            ['kota_id' => '13', 'kecamatan' => 'SUBANG'],
            ['kota_id' => '13', 'kecamatan' => 'KALIJATI'],
            ['kota_id' => '13', 'kecamatan' => 'DAWUAN'],
            ['kota_id' => '13', 'kecamatan' => 'CIPEUNDEUY'],
            ['kota_id' => '13', 'kecamatan' => 'PABUARAN'],
            ['kota_id' => '13', 'kecamatan' => 'PATOKBEUSI'],
            ['kota_id' => '13', 'kecamatan' => 'PURWADADI'],
            ['kota_id' => '13', 'kecamatan' => 'CIKAUM'],
            ['kota_id' => '13', 'kecamatan' => 'PAGADEN'],
            ['kota_id' => '13', 'kecamatan' => 'PAGADEN BARAT'],
            ['kota_id' => '13', 'kecamatan' => 'CIPUNAGARA'],
            ['kota_id' => '13', 'kecamatan' => 'COMPRENG'],
            ['kota_id' => '13', 'kecamatan' => 'BINONG'],
            ['kota_id' => '13', 'kecamatan' => 'TAMBAKDAHAN'],
            ['kota_id' => '13', 'kecamatan' => 'CIASEM'],
            ['kota_id' => '13', 'kecamatan' => 'PAMANUKAN'],
            ['kota_id' => '13', 'kecamatan' => 'SUKASARI'],
            ['kota_id' => '13', 'kecamatan' => 'PUSAKANAGARA'],
            ['kota_id' => '13', 'kecamatan' => 'PUSAKAJAYA'],
            ['kota_id' => '13', 'kecamatan' => 'LEGONKULON'],
            ['kota_id' => '13', 'kecamatan' => 'BLANAKAN'],
            ['kota_id' => '14', 'kecamatan' => 'JATILUHUR'],
            ['kota_id' => '14', 'kecamatan' => 'SUKASARI'],
            ['kota_id' => '14', 'kecamatan' => 'MANIIS'],
            ['kota_id' => '14', 'kecamatan' => 'TEGAL WARU'],
            ['kota_id' => '14', 'kecamatan' => 'PLERED'],
            ['kota_id' => '14', 'kecamatan' => 'SUKATANI'],
            ['kota_id' => '14', 'kecamatan' => 'DARANGDAN'],
            ['kota_id' => '14', 'kecamatan' => 'BOJONG'],
            ['kota_id' => '14', 'kecamatan' => 'WANAYASA'],
            ['kota_id' => '14', 'kecamatan' => 'KIARAPEDES'],
            ['kota_id' => '14', 'kecamatan' => 'PASAWAHAN'],
            ['kota_id' => '14', 'kecamatan' => 'PONDOK SALAM'],
            ['kota_id' => '14', 'kecamatan' => 'PURWAKARTA'],
            ['kota_id' => '14', 'kecamatan' => 'BABAKANCIKAO'],
            ['kota_id' => '14', 'kecamatan' => 'CAMPAKA'],
            ['kota_id' => '14', 'kecamatan' => 'CIBATU'],
            ['kota_id' => '14', 'kecamatan' => 'BUNGURSARI'],
            ['kota_id' => '15', 'kecamatan' => 'PANGKALAN'],
            ['kota_id' => '15', 'kecamatan' => 'TEGALWARU'],
            ['kota_id' => '15', 'kecamatan' => 'CIAMPEL'],
            ['kota_id' => '15', 'kecamatan' => 'TELUKJAMBE TIMUR'],
            ['kota_id' => '15', 'kecamatan' => 'TELUKJAMBE BARAT'],
            ['kota_id' => '15', 'kecamatan' => 'KLARI'],
            ['kota_id' => '15', 'kecamatan' => 'CIKAMPEK'],
            ['kota_id' => '15', 'kecamatan' => 'PURWASARI'],
            ['kota_id' => '15', 'kecamatan' => 'TIRTAMULYA'],
            ['kota_id' => '15', 'kecamatan' => 'JATISARI'],
            ['kota_id' => '15', 'kecamatan' => 'BANYUSARI'],
            ['kota_id' => '15', 'kecamatan' => 'KOTABARU'],
            ['kota_id' => '15', 'kecamatan' => 'CILAMAYA WETAN'],
            ['kota_id' => '15', 'kecamatan' => 'CILAMAYA KULON'],
            ['kota_id' => '15', 'kecamatan' => 'LEMAHABANG'],
            ['kota_id' => '15', 'kecamatan' => 'TALAGASARI'],
            ['kota_id' => '15', 'kecamatan' => 'MAJALAYA'],
            ['kota_id' => '15', 'kecamatan' => 'KARAWANG TIMUR'],
            ['kota_id' => '15', 'kecamatan' => 'KARAWANG BARAT'],
            ['kota_id' => '15', 'kecamatan' => 'RAWAMERTA'],
            ['kota_id' => '15', 'kecamatan' => 'TEMPURAN'],
            ['kota_id' => '15', 'kecamatan' => 'KUTAWALUYA'],
            ['kota_id' => '15', 'kecamatan' => 'RENGASDENGKLOK'],
            ['kota_id' => '15', 'kecamatan' => 'JAYAKERTA'],
            ['kota_id' => '15', 'kecamatan' => 'PEDES'],
            ['kota_id' => '15', 'kecamatan' => 'CILEBAR'],
            ['kota_id' => '15', 'kecamatan' => 'CIBUAYA'],
            ['kota_id' => '15', 'kecamatan' => 'TIRTAJAYA'],
            ['kota_id' => '15', 'kecamatan' => 'BATUJAYA'],
            ['kota_id' => '15', 'kecamatan' => 'PAKISJAYA'],
            ['kota_id' => '16', 'kecamatan' => 'SETU'],
            ['kota_id' => '16', 'kecamatan' => 'SERANG BARU'],
            ['kota_id' => '16', 'kecamatan' => 'CIKARANG PUSAT'],
            ['kota_id' => '16', 'kecamatan' => 'CIKARANG SELATAN'],
            ['kota_id' => '16', 'kecamatan' => 'CIBARUSAH'],
            ['kota_id' => '16', 'kecamatan' => 'BOJONGMANGU'],
            ['kota_id' => '16', 'kecamatan' => 'CIKARANG TIMUR'],
            ['kota_id' => '16', 'kecamatan' => 'KEDUNGWARINGIN'],
            ['kota_id' => '16', 'kecamatan' => 'CIKARANG UTARA'],
            ['kota_id' => '16', 'kecamatan' => 'KARANGBAHAGIA'],
            ['kota_id' => '16', 'kecamatan' => 'CIBITUNG'],
            ['kota_id' => '16', 'kecamatan' => 'CIKARANG BARAT'],
            ['kota_id' => '16', 'kecamatan' => 'TAMBUN SELATAN'],
            ['kota_id' => '16', 'kecamatan' => 'TAMBUN UTARA'],
            ['kota_id' => '16', 'kecamatan' => 'BABELAN'],
            ['kota_id' => '16', 'kecamatan' => 'TARUMAJAYA'],
            ['kota_id' => '16', 'kecamatan' => 'TAMBELANG'],
            ['kota_id' => '16', 'kecamatan' => 'SUKAWANGI'],
            ['kota_id' => '16', 'kecamatan' => 'SUKATANI'],
            ['kota_id' => '16', 'kecamatan' => 'SUKAKARYA'],
            ['kota_id' => '16', 'kecamatan' => 'PEBAYURAN'],
            ['kota_id' => '16', 'kecamatan' => 'CABANGBUNGIN'],
            ['kota_id' => '16', 'kecamatan' => 'MUARA GEMBONG'],
            ['kota_id' => '17', 'kecamatan' => 'RONGGA'],
            ['kota_id' => '17', 'kecamatan' => 'GUNUNGHALU'],
            ['kota_id' => '17', 'kecamatan' => 'SINDANGKERTA'],
            ['kota_id' => '17', 'kecamatan' => 'CILILIN'],
            ['kota_id' => '17', 'kecamatan' => 'CIHAMPELAS'],
            ['kota_id' => '17', 'kecamatan' => 'CIPONGKOR'],
            ['kota_id' => '17', 'kecamatan' => 'BATUJAJAR'],
            ['kota_id' => '17', 'kecamatan' => 'SAGULING'],
            ['kota_id' => '17', 'kecamatan' => 'CIPATAT'],
            ['kota_id' => '17', 'kecamatan' => 'PADALARANG'],
            ['kota_id' => '17', 'kecamatan' => 'NGAMPRAH'],
            ['kota_id' => '17', 'kecamatan' => 'PARONGPONG'],
            ['kota_id' => '17', 'kecamatan' => 'LEMBANG'],
            ['kota_id' => '17', 'kecamatan' => 'CISARUA'],
            ['kota_id' => '17', 'kecamatan' => 'CIKALONG WETAN'],
            ['kota_id' => '17', 'kecamatan' => 'CIPEUNDEUY'],
            ['kota_id' => '18', 'kecamatan' => 'CIMERAK'],
            ['kota_id' => '18', 'kecamatan' => 'CIJULANG'],
            ['kota_id' => '18', 'kecamatan' => 'CIGUGUR'],
            ['kota_id' => '18', 'kecamatan' => 'LANGKAPLANCAR'],
            ['kota_id' => '18', 'kecamatan' => 'PARIGI'],
            ['kota_id' => '18', 'kecamatan' => 'SIDAMULIH'],
            ['kota_id' => '18', 'kecamatan' => 'PANGANDARAN'],
            ['kota_id' => '18', 'kecamatan' => 'KALIPUCANG'],
            ['kota_id' => '18', 'kecamatan' => 'PADAHERANG'],
            ['kota_id' => '18', 'kecamatan' => 'MANGUNJAYA'],
            ['kota_id' => '19', 'kecamatan' => 'BOGOR SELATAN'],
            ['kota_id' => '19', 'kecamatan' => 'BOGOR TIMUR'],
            ['kota_id' => '19', 'kecamatan' => 'BOGOR UTARA'],
            ['kota_id' => '19', 'kecamatan' => 'BOGOR TENGAH'],
            ['kota_id' => '19', 'kecamatan' => 'BOGOR BARAT'],
            ['kota_id' => '19', 'kecamatan' => 'TANAH SEREAL'],
            ['kota_id' => '20', 'kecamatan' => 'BAROS'],
            ['kota_id' => '20', 'kecamatan' => 'LEMBURSITU'],
            ['kota_id' => '20', 'kecamatan' => 'CIBEUREUM'],
            ['kota_id' => '20', 'kecamatan' => 'CITAMIANG'],
            ['kota_id' => '20', 'kecamatan' => 'WARUDOYONG'],
            ['kota_id' => '20', 'kecamatan' => 'GUNUNG PUYUH'],
            ['kota_id' => '20', 'kecamatan' => 'CIKOLE'],
            ['kota_id' => '21', 'kecamatan' => 'BANDUNG KULON'],
            ['kota_id' => '21', 'kecamatan' => 'BABAKAN CIPARAY'],
            ['kota_id' => '21', 'kecamatan' => 'BOJONGLOA KALER'],
            ['kota_id' => '21', 'kecamatan' => 'BOJONGLOA KIDUL'],
            ['kota_id' => '21', 'kecamatan' => 'ASTANAANYAR'],
            ['kota_id' => '21', 'kecamatan' => 'REGOL'],
            ['kota_id' => '21', 'kecamatan' => 'LENGKONG'],
            ['kota_id' => '21', 'kecamatan' => 'BANDUNG KIDUL'],
            ['kota_id' => '21', 'kecamatan' => 'BUAHBATU'],
            ['kota_id' => '21', 'kecamatan' => 'RANCASARI'],
            ['kota_id' => '21', 'kecamatan' => 'GEDEBAGE'],
            ['kota_id' => '21', 'kecamatan' => 'CIBIRU'],
            ['kota_id' => '21', 'kecamatan' => 'PANYILEUKAN'],
            ['kota_id' => '21', 'kecamatan' => 'UJUNG BERUNG'],
            ['kota_id' => '21', 'kecamatan' => 'CINAMBO'],
            ['kota_id' => '21', 'kecamatan' => 'ARCAMANIK'],
            ['kota_id' => '21', 'kecamatan' => 'ANTAPANI'],
            ['kota_id' => '21', 'kecamatan' => 'MANDALAJATI'],
            ['kota_id' => '21', 'kecamatan' => 'KIARACONDONG'],
            ['kota_id' => '21', 'kecamatan' => 'BATUNUNGGAL'],
            ['kota_id' => '21', 'kecamatan' => 'SUMUR BANDUNG'],
            ['kota_id' => '21', 'kecamatan' => 'ANDIR'],
            ['kota_id' => '21', 'kecamatan' => 'CICENDO'],
            ['kota_id' => '21', 'kecamatan' => 'BANDUNG WETAN'],
            ['kota_id' => '21', 'kecamatan' => 'CIBEUNYING KIDUL'],
            ['kota_id' => '21', 'kecamatan' => 'CIBEUNYING KALER'],
            ['kota_id' => '21', 'kecamatan' => 'COBLONG'],
            ['kota_id' => '21', 'kecamatan' => 'SUKAJADI'],
            ['kota_id' => '21', 'kecamatan' => 'SUKASARI'],
            ['kota_id' => '21', 'kecamatan' => 'CIDADAP'],
            ['kota_id' => '22', 'kecamatan' => 'HARJAMUKTI'],
            ['kota_id' => '22', 'kecamatan' => 'LEMAHWUNGKUK'],
            ['kota_id' => '22', 'kecamatan' => 'PEKALIPAN'],
            ['kota_id' => '22', 'kecamatan' => 'KESAMBI'],
            ['kota_id' => '22', 'kecamatan' => 'KEJAKSAN'],
            ['kota_id' => '23', 'kecamatan' => 'PONDOKGEDE'],
            ['kota_id' => '23', 'kecamatan' => 'JATISAMPURNA'],
            ['kota_id' => '23', 'kecamatan' => 'PONDOKMELATI'],
            ['kota_id' => '23', 'kecamatan' => 'JATIASIH'],
            ['kota_id' => '23', 'kecamatan' => 'BANTARGEBANG'],
            ['kota_id' => '23', 'kecamatan' => 'MUSTIKAJAYA'],
            ['kota_id' => '23', 'kecamatan' => 'BEKASI TIMUR'],
            ['kota_id' => '23', 'kecamatan' => 'RAWALUMBU'],
            ['kota_id' => '23', 'kecamatan' => 'BEKASI SELATAN'],
            ['kota_id' => '23', 'kecamatan' => 'BEKASI BARAT'],
            ['kota_id' => '23', 'kecamatan' => 'MEDAN SATRIA'],
            ['kota_id' => '23', 'kecamatan' => 'BEKASI UTARA'],
            ['kota_id' => '24', 'kecamatan' => 'SAWANGAN'],
            ['kota_id' => '24', 'kecamatan' => 'BOJONGSARI'],
            ['kota_id' => '24', 'kecamatan' => 'PANCORAN MAS'],
            ['kota_id' => '24', 'kecamatan' => 'CIPAYUNG'],
            ['kota_id' => '24', 'kecamatan' => 'SUKMA JAYA'],
            ['kota_id' => '24', 'kecamatan' => 'CILODONG'],
            ['kota_id' => '24', 'kecamatan' => 'CIMANGGIS'],
            ['kota_id' => '24', 'kecamatan' => 'TAPOS'],
            ['kota_id' => '24', 'kecamatan' => 'BEJI'],
            ['kota_id' => '24', 'kecamatan' => 'LIMO'],
            ['kota_id' => '24', 'kecamatan' => 'CINERE'],
            ['kota_id' => '25', 'kecamatan' => 'CIMAHI SELATAN'],
            ['kota_id' => '25', 'kecamatan' => 'CIMAHI TENGAH'],
            ['kota_id' => '25', 'kecamatan' => 'CIMAHI UTARA'],
        ];
        DB::table('kecamatans')->insert($kecamatan);
    }
}
